dist: xenial
notifications:
  email: false
language: rust
rust:
  - nightly
cache:
  cargo: true
  directories:
  - "$HOME/.rustup"
addons:
  postgresql: '9.5'
  apt:
    packages:
    - curl
    - libpq-dev
    - pkg-config
before_install:
  - rustup component add clippy
script:
  - cargo clippy --all --examples --tests
